### PR TITLE
HD Textures

### PR DESCRIPTION
**Pull request by DarioSamo**
I'm putting up this PR to unblock texture pack developers from making stuff compatible for RT64 while I polish the feature for its first public release.

## TODO

- [x] Asynchronous streaming support
- [x] Extraction of lowest quality mipmaps to use as the basis for streaming support.
- [x] Solve any compatibility issues from textures that don't match the width and height of their Rice counterparts yet.
- [x] Fix this regression (https://github.com/Zelda64Recomp/Zelda64Recomp/issues/430)
- [x] Review texture upload randomly corrupting files sometimes.
- [x] Investigate crash under D3D12 that can happen when loading a directory.
- [x] Operations filters.
- [x] ZIP File Support.
- [x] Test using memory file mapping with the Zip archive to use as the shared file handle instead of using the contexts.
- [x] LRU Cache.
- [x] Investigate bug caused by non-native samplers [here](https://github.com/rt64/rt64/pull/34#issuecomment-2246785039).
- [x] Add unload button.
- [x] Support loading multiple packs through a filesystem abstraction.

Only available for experimental testing through the developer mode menu at the moment (graphics.json in Zelda64Recompiled). You can find an example of a compatible texture pack here (**download the repository**).

* MM Reloaded by GhostlyDark: https://github.com/GhostlyDark/MM-Reloaded

You can generate mappings for other games by using the texture_hasher tool along with the built-in texture dumper.

## Instructions

**These instructions are by no means meant for final end users. This is only for people who wish to experiment as early as possible. This workflow won't resemble at all what end users will have to do.**

- In case you don't have this, %LocalAppData/Zelda64Recompiled/graphics.json should have developer_mode set to true.
- Extract your texture pack somewhere. Convert them to DDS if possible. **PNG texture packs are strongly not recommended.**
- Start the game, press F1, go to the textures tab, and click on "Load directory". Point it to the texture pack directory (rt64.json must be present in the directory). It might take a bit to load if it needs to scan it the first time.

## NOTES

* **DDS are supported and preferred**. No mipmaps are generated for PNG textures. **Avoid PNG if possible**. 

* DDS offers compressed block formats that will occupy nearly 1/4th of the size in VRAM it'd take for the equivalent RGBA32 PNG texture for next to no quality loss when using formats like BC7. **DDS will not only load much faster, it'll use less VRAM and perform better too**.

* Various compatibility issues with GlideN64 texture packs are expected and might need to be reworked either due to how GlideN64 parses Intensity textures only on the red channel or due to texture shifting hacks not being required in RT64 to align multi texturing.

* F4 will toggle the replacements being shown while in developer mode.

### CODE REVIEW

**Comment by EliazarGtez** [comment]
I don't find the "texture pack" tab. Where is it?

Thanks

**Comment by GhostlyDark** [comment]
Missing rice matches that can be replaced manually:
- Astral Observatory (telescope)
- Bean Seller (shoes)
- Deku Salesman (bag)
- Great Bay Temple (faucet room, part of the switch)
- Music Box House (downstairs, left side - part of the grey metal)
- Wart (brownish backside)

Ikana Castle (exit Benath the Well)
image

Goron Shop
image

Lost Woods
image
image

Great Bay Temple (exterior, scene 34)
image
image

Ikana Canyon (large tree)
image

**Comment by GhostlyDark** [comment]
Only some parts of the Granny Story images are matched, most of them not.
image

**Comment by GhostlyDark** [comment]
With rice format, one texture dump modifies two spots in the Lottery Shop. rt64 has unique hashes for these.
Probably an inaccuracy with Rice, but I thought it'd be worth mentioning regardless.

rice: `d144e4e4#4#1`
rt64 target: `652784651c9c65f4`
rt64 box: `3afc0ae708d3e5ac`

image

**Comment by GhostlyDark** [comment]
This wall in Sakon's Hideout gets corrupted when moving the camera. The rt64 hash doesn't change however.
Dolphin generates duplicates in this room, GLideN64 does not.

rice: `ad40ef9f#0#2`
rt64: `bd9d9af7484c7f52`

image
image

**Comment by GhostlyDark** [comment]
Some more general thoughts:

1. Re-using the same `path` to a duplicate texture doesn't work right now. Neither do multiple rice matches (one rice hash, multiple rt64 hashes) work, only the first one in the list.

Doesn't work (only loads the first entry):
```
        {
            "hashes": {
                "rice": "d144e4e4#4#1",
                "rt64v1": "3afc0ae708d3e5ac"
            },
            "life": "pool",
            "load": "stream",
            "path": "rt64\\d144e4e4#4#1.png"
        },
        {
            "hashes": {
                "rice": "d144e4e4#4#1",
                "rt64v1": "652784651c9c65f4"
            },
            "life": "pool",
            "load": "stream",
            "path": "rt64\\d144e4e4#4#1.png"
        },
```

Works:
```
        {
            "hashes": {
                "rice": "d144e4e4#4#1",
                "rt64v1": "3afc0ae708d3e5ac"
            },
            "life": "pool",
            "load": "stream",
            "path": "rt64\\d144e4e4#4#1_3afc0ae708d3e5ac.png"
        },
        {
            "hashes": {
                "rice": "d144e4e4#4#1",
                "rt64v1": "652784651c9c65f4"
            },
            "life": "pool",
            "load": "stream",
            "path": "rt64\\d144e4e4#4#1_652784651c9c65f4.png"
        },
```

2. `path` seems to require a file extension `.png` or `.dds` which currently requires editing the json file after converting textures
3. Thoughts on auto loading files that are named after a usable rt64 hash even without a json file?

**Comment by DarioSamo** [comment]
> Missing rice matches that can be replaced manually:
> 
>     * Astral Observatory (telescope)
> 
>     * Bean Seller (shoes)
> 
>     * Deku Salesman (bag)
> 
>     * Great Bay Temple (faucet room, part of the switch)
> 
>     * Music Box House (downstairs, left side - part of the grey metal)
> 
>     * Wart (brownish backside)
> 

These shared in common that they had incorrect masks that made RT64 fall back to using TMEM only, which previously did not support texture replacements. I just pushed an update to fix these, allowing the dumper to go through even if the parameters aren't entirely valid.

**Comment by DarioSamo** [comment]
> With rice format, one texture dump modifies two spots in the Lottery Shop. rt64 has unique hashes for these. Probably an inaccuracy with Rice, but I thought it'd be worth mentioning regardless. Also has two hashes using Dolphin.
> 
> rice: `d144e4e4#4#1` rt64 target: `652784651c9c65f4` rt64 box: `3afc0ae708d3e5ac`
> 

Rice is technically kind of correct here, but only because this is a case where the hashes will only be different if you emulate TMEM properly.

One line of the texture can't fully fit into one line of TMEM, so this is an edge case where the hash must only be done in the bytes that are covered by the mask line by line to avoid hashing garbage. This is a small improvement that can be made to the hashing algorithm, although it'll hurt performance on textures that are not wide enough to fit one line of TMEM.

**Comment by DarioSamo** [comment]
> This wall in Sakon's Hideout changes appearance if the camera is moving, resulting in duplicate textures. Dolphin generates duplicates in this room, GLideN64 does not.

Confirmed, unsure as to how GlideN64 doesn't generate duplicate dumps though, as the texture does visually change. I think we have to accept this one as valid but it's probably worth a check on the decompilation as to why exactly it does this.

**Comment by DarioSamo** [comment]
> Only some parts of the Granny Story images are matched, most of them not.
> 
> Each tile is 320x6. GLideN64 dumps 48 tiles, rt64 has 40 tiles. GLideN64 dumps need a 1px overlap to achieve the 320x240 full image size: `48*6=288 - 48 overlap = 240`. rt64 goes straight to `40*6=240`.
> 
> With that in mind, the rice dumps shouldn't have matched at all to begin with.

We should confirm in LLE mode what the textures are supposed to be first, in case this is using S2DEX.

**Comment by DarioSamo** [comment]
>     1. Re-using the same `path` to a duplicate texture doesn't work right now. Neither do multiple rice matches (one rice hash, multiple rt64 hashes) work, only the first one in the list.

This one should be fixed now.

**Comment by DarioSamo** [comment]
>     2. `path` seems to require a file extension `.png` or `.dds` which currently requires editing the json file after converting textures

I agree to take out the extension of the file, it seems irrelevant to the purpose of the database. RT64 will try to look for DDS first and PNG later in order of preference.

**Comment by DarioSamo** [comment]
> One line of the texture can't fully fit into one line of TMEM, so this is an edge case where the hash must only be done in the bytes that are covered by the mask line by line to avoid hashing garbage. This is a small improvement that can be made to the hashing algorithm, although it'll hurt performance on textures that are not wide enough to fit one line of TMEM.

This probably needs to be sorted out before we continue making more dumps.

**Comment by DarioSamo** [comment]
D3D12 is not enabling anisotropic filtering properly (driver setting can override this).

**Comment by DarioSamo** [comment]
> > With rice format, one texture dump modifies two spots in the Lottery Shop. rt64 has unique hashes for these. Probably an inaccuracy with Rice, but I thought it'd be worth mentioning regardless. Also has two hashes using Dolphin.
> > rice: `d144e4e4#4#1` rt64 target: `652784651c9c65f4` rt64 box: `3afc0ae708d3e5ac`
> 
> Rice is technically kind of correct here, but only because this is a case where the hashes will only be different if you emulate TMEM properly.
> 
> One line of the texture can't fully fit into one line of TMEM, so this is an edge case where the hash must only be done in the bytes that are covered by the mask line by line to avoid hashing garbage. This is a small improvement that can be made to the hashing algorithm, although it'll hurt performance on textures that are not wide enough to fit one line of TMEM.

So this is not as simple as I expected. What I did say _is_ true, but there's an additional wrinkle to those lottery textures: they're incorrectly loaded using load block as 16 bytes in total, but the draw tile is configured with a line of 1, so it must step 8 bytes for every row. Therefore it can only sample what's being leaked from a previous load. As far as I can tell, this must stay as unique hashes despite Rice detecting it as one from the load itself.

**Comment by DarioSamo** [comment]
> > ```
> > 2. `path` seems to require a file extension `.png` or `.dds` which currently requires editing the json file after converting textures
> > ```
> 
> I agree to take out the extension of the file, it seems irrelevant to the purpose of the database. RT64 will try to look for DDS first and PNG later in order of preference.

This is handled now as of the latest commit.

**Comment by DarioSamo** [comment]
Some pretty significant additions have been pushed like support for a low mipmap cache that is used until the full version of the texture is loaded and texture streaming. Mip caches can be generated with the `texture_packer` tool.

**Comment by DarioSamo** [comment]
Pushed texture pack support and operation filters.

**Comment by DarioSamo** [comment]
Pushed zstd support.

**Comment by DarioSamo** [comment]
This particular DDS does not seem to go through the proper fallback when native samplers are not used. To investigate.
image

**Comment by DarioSamo** [comment]
Not actually a sampler bug, the texture itself seems to have alpha channels as 0 for whatever reason on these lower pixels on the lowest mipmap.

image

**Comment by DarioSamo** [comment]
Pushed support for loading multiple texture packs at once.

**Pull request merged**
